version: '3.8'

services:
  # Service API Express
  api:
    image: dockregistry.xju.fr/baby-check-api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: baby-check-api
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SERVER_PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - baby-check-network

  # Service Client Vue.js
  client:
    image: dockregistry.xju.fr/baby-check-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baby-check-client
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - baby-check-network

networks:
  baby-check-network:
    driver: bridge
